### PR TITLE
Base3

### PR DESCRIPTION
**Pull request by erezfree29**
I have built a responsive clone for the next webpage.
The page was initially designed for mobile view and using media queries that alter the CSS for a bigger screen, I have managed to achieve responsiveness.
I have also made sure the page is not only responsive but behaves in the exact same way as the original using grid view which allowed me to display more elements across the width of the page in accordance with space availability.

p.s I am submitting this project alone as my partner has notified me that he is leaving the program.

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi Erez :wave: 

You have improved from your previous submissions, great work. But there are few project requirements you missed.

**For navigation bar section**:
  At a screen greater than 1106px: 

- The links on the lower navigation bar are not properly aligned. 
- The search icon should not overlap the **Top 3 articles section**

At a small screen size:
- The hamburger button icon should appear on the right side of the navigation bar.

**Top 3 articles section**

For large screen:
- There should be a **TNW logo** at the background of the left grid of the image.

At a medium screen: 

- The logo should disappear.

**Apps gear tech section**

- For the Large screen, the characters, showing the name and number of days were overlapping the images, do fix that. Below is the image for reference

over


**Latest deal section**
- For the large screen, add a space between each image card.

#### Make these changes, then submit another form for a code review

Always use the [website](https://thenextweb.com/) for reference

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ]  KIndly work on all requirement as requested by previous TSE.
 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by erezfree29** [comment]
Hello I have worked on the requirements 
two of them I didn't understand

1)The hamburger button icon should appear on the right side of the navigation bar.

it does appear 

2)At a medium screen:

The logo should disappear.

It does not disappear on the original website 

I have fixed the others please kindly advise what is still outstaning.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**
- [ ] Please make changes requested by previous TSE and then request for code review

- [ ] there is an overflowing of text in your web page please fix that
**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by erezfree29** [comment]
Hello 

I have implemented the changes apart from two which I did not  understand 

1)The hamburger button icon should appear on the right side of the navigation bar.
it does appear

2)At a medium screen:
The logo should disappear.
It does not disappear on the original website


you also wrote the there is an overflowing of text on which screen size?

does the text-overflow to the right?

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @erezfree29 :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
